// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcxhmjhqfpnqhpiboaie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjeGhtamhxZnBucWhwaWJvYWllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNzc4ODQsImV4cCI6MjA2Nzc1Mzg4NH0.h3HMft63BHig9gIT6oj6AfADwStpWbE9vtFH2PynCmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});